name: KETOGAINS
favicon: null
layout_spectrum: 0.8575964102055877
typography_spectrum: 0.8344588382169604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.27914293692447245
  lightness: 0.7574130974244326
  saturation: 0.05740052368491888
  rhythmicContrast: 0.8676954782567918
purpose: []
